### PR TITLE
add Kelvin filter

### PR DESCRIPTION
**Pull request by shelune**

### CODE REVIEW

**Comment by una** [comment]
please get this updated with master and if you can, please rebase your commits into one!

**Comment by shelune** [comment]
Can I skip the squashing stuff? Seems like there're not my commits only but yours as well so things messed up heavily and I don't know how to deal with them :<

Updated thou.

**Comment by una** [comment]
I'm happy to help you through it -- right now it only looks like your changes being pushed. Check out this post on squashing commits: http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by shelune** [comment]
please check if I also need to add the twig file :)

**Comment by una** [comment]
Nice job with the rebase! I Would add it to the *test/index.twig*

**Comment by shelune** [comment]
Thank you!

**Comment by una** [comment]
Sorry this filter's code doesn't currently resemble the Kelvin tests either -- 

screen shot 2015-12-18 at 11 26 26 pm

when I didnt have a `::before` background, it looked a bit closer, though! Maybe try that? :smile:

**Pull request closed without merging**
