### PR TITLE
re-added slumber

### PR DESCRIPTION
**Pull request by shelune**
I modified the filter a bit. What do you think?
slumber-sample

Also, about the test twig file, I figured the line 38 of site/test/index.twig

>            <figure class="{{f.name}}">

Shouldn't it be

>            <figure class="{{f.usage}}">

instead so the figures get the class name in lowercase instead of capitalized? (e.g 'slumber' instead of 'Slumber')

### CODE REVIEW

**Comment by una** [comment]
Wow, i just fixed the f.usage problem :) and yes i think its almost there -- maybe desaturate it a tiny bit?

**Comment by shelune** [comment]
Hope this suffices!

**Comment by una** [comment]
I think this looks pretty good! Thanks @shelune -- make sure its up to date with master (resolve conflicts) and i'll merge it

**Comment by shelune** [comment]
Fixed the conflicts and merged into 1 commit for you

**Comment by una** [comment]
You're the best!

**Pull request merged**
