### PR TITLE
Cacti img fix

### PR DESCRIPTION
**Pull request by 526avijitgupta**

### CODE REVIEW

**Comment by una** [comment]
This was being discussed in an issue before the issues became spammed -- I don't think it's a problem anymore

**Comment by 526avijitgupta** [comment]
@una Sorry, I think I am a little confused. There is a file named `cacti.JPG` while, [here](https://github.com/una/CSSgram/blob/c0b9347c89ac91c8f2f38996c7c3766fc4282de7/site/index.html#L32) there is a reference to `.jpg`  one.

**Comment by una** [comment]
https://github.com/una/CSSgram/tree/gh-pages/img

**Comment by 526avijitgupta** [comment]
@una It seems that this is in the `gh-pages` branch, not in `master`. In `master`, there is no file named `cacti.jpg`.

**Comment by una** [comment]
I fixed that -- it was due to SSH issues i was having. Thanks for pointing it out! :smile:

**Pull request closed without merging**
