### PR TITLE
Bugg

### PR DESCRIPTION
**Pull request by Trollodeboy**
Bugg filter

### CODE REVIEW

**Comment by gr2m** [comment]
@una this is one of several accounts that I’ve seen in the past few days (since Hacktoberfest page went online and linked our repositories) that sends these nonsense PRs.

Please, don’t let them get a T-Shirt, k?

See https://github.com/hoodiehq/hoodie/pull/584, https://github.com/atom/atom/pull/12837, https://github.com/laravel/laravel/pull/3974

This makes me so sad 😿

**Comment by MarshallOfSound** [comment]
@gr2m Tag all stupid PR's with invalid and hopefully we can get DigitalOcean to ignore all `invalid` PR's.

This is what `atom` and `electron` are doing

**Comment by gr2m** [comment]
@MarshallOfSound I report all GitHub accounts that do that, I hope they will review accounts before sending them T-Shirts :)

**Comment by una** [comment]
@gr2m @MarshallOfSound I'm going to follow up internally about this

**Pull request closed without merging**
