### PR TITLE
added maven filter

### PR DESCRIPTION
**Pull request by LadyCarni**
re: https://github.com/una/CSSgram/issues/127

screen shot 2016-11-01 at 10 27 20 am

### CODE REVIEW

**Comment by una** [comment]
Hey do you mind also taking a screenshot of the `/test` page with all of these PRs?

**Comment by LadyCarni** [comment]
Yep, I'll get those up attached ASAP :)

**Comment by LadyCarni** [comment]
Updated PR comment with visual.

**Comment by una** [comment]
Awesome, going to merge this in! :)

**Pull request merged**
