### PR TITLE
Updated README (Issue #215)

### PR DESCRIPTION
**Pull request by conscou**
Ignore the first commit about randomized Outer Sailor Scout--that was for another project I was working on.

Addressing issue #215

### CODE REVIEW

**Comment by jamesmacfie** [comment]
@conscou Git rebasing is a good option for getting rid of that other commit. Heres a guide that's helpful https://www.atlassian.com/git/tutorials/rewriting-history/

**Comment by una** [comment]
Hey-- im getting a lot of redundant requests to update this section of the README, and it seems not super useful considering the issue cue is for that! 

I'd love for you to submit another PR though :) maybe try checking out how to edit the filters themselves to improve them!

**Comment by conscou** [comment]
@una sorry I'm new to contributing to open source projects and I wanted to start out small. There just seems to be so much happening and accomplished already and I really don't know how to improve any of them that's not changing something like saturation...which would just make it a different filter...

**Comment by shivamluthra** [comment]
@una hi there! , i actually wanted to contribute to your repository and as i am new to open source contributions, can you please guide me how to start from scratch ? Also, please help me know the name of file where all these filter effects are being set.
Thanks.

**Pull request closed without merging**
