### PR TITLE
Fixed duplicate code

### PR DESCRIPTION
**Pull request by DeMuu**
replaced the extend approach with mixins to avoid generating.

I'm really sorry for the messed up commits. I had some problems with my Git tool before the pull request was created 🙇 😞

### CODE REVIEW

**Comment by DeMuu** [comment]
It's not perfect yet as there's still redundant attributes but the built file size decreases a lot. On top of that we can avoid all the overwrites that existed before.

**Comment by una** [comment]
Hey! Thanks for this PR--just curious where the duplication you found was coming from? extending an invisible placeholder selector to me is reducing redundancy, but we also wanted to build individual .css files for each filter (as well as an overall file) for inclusion.

I think you have valid intention for reducing redundancy, just wondering how exactly?

**Comment by DeMuu** [comment]
When you take a look at `cssgram.css` right now it has more than 4k lines. The reason is that for each filter the same rules are added again and again. So we have something like this

```
.aden,
.inkwell,
.perpetua,
.reyes,
.gingham,
.toaster,
.walden,
.hudson,
.earlybird,
.mayfair,
.lofi,
._1977,
.brooklyn,
.xpro2,
.nashville,
.lark,
.moon,
.clarendon,
.willow,
.rise,
.slumber,
.brannan,
.valencia,
.kelvin {
  position: relative; }
```

more than once.
Therefore if users want to include the whole file and not just single filter files they get redundant code:
image

The changes do not change anything inside the single filter files and only really affect the compiled `cssgram.css`

There's still room to improve as with my changes now we still generate a `position: relative` rule for each filter and this should also be fixed but I couldn't really wrap my head around a way to do it.

The perfect result IMO should be something like:

```
.brannan, .clarendon, .amaro, ... { position: relative; }
.brennan, .clarendon, .amaro, ... { content:''; ... }
```

The reduced file size would make it way more attractive for people thinking about performance I suppose.

Hope I could make it kind of clear 😅

**Comment by una** [comment]
Wow, yeah I didn't realize it was repeating so much, as I was only looking at the minified file. This is a great update.

Would you mind rebasing to resolve conflicts? I'd love to get this in :)

**Comment by una** [comment]
Sorry I think a new commit may have caused another conflict 😞

**Comment by DeMuu** [comment]
@una no problem^^. fixed the affected file 🙃

**Comment by una** [comment]
yayyyy!

**Comment by Praseetha-KR** [comment]
Now the builds are much faster, nice work! 👏

**Pull request merged**
