### PR TITLE
Make this library (SASS source) extensible.

### PR DESCRIPTION
**Pull request by bunomonteiro**
**Q: What this PR fixes?**
**A:** Allows add filter to an existing CSSgram filter (only using SASS)

**Q: Why?**
**A:** CSS3 filter property does not allow inheritance, you cannot 'add' new filters keeping the existing filters

Before:
```
figure {
  @extend %aden;
  &:hover{
    filter: blur(2px); // overrides Aden filter, now has only blur filter
  }
}
```

Now:
```
figure {
  @extend %aden; // or @include aden;
  &:hover{
    @include aden(blur(2px) /*...*/); // Aden filter still works, but now blur filter was 'added'
  }
}
```

_PS: Now comments are compatible with SassDoc._

:smile:

### CODE REVIEW

**Comment by una** [comment]
@bunomonteiro, this is a great point -- do you mind updating the docs as a part of this PR with the updated usage?

**Comment by bunomonteiro** [comment]
Of course! Why not? :wink:

**Comment by una** [comment]
Sorry for the wait on this -- I've been thinking it through since this is a major addition! I do like it a lot and it's backwards compatible with an additional consumption model I definitely agree is important to have.

Thank you for your careful consideration and documentation! :sparkles: This is great!

**Comment by bunomonteiro** [comment]
uhuu! 

No need to apologize, it did not take much. It took the time needed for a good job done. :smiley:

uh, by the way, I think the site's title is wrong :wink:

**Pull request merged**
