### PR TITLE
Added Contributing file with information

### PR DESCRIPTION
**Pull request by Bobeta**
I happened to miss the contribution section in the Readme while looking through the project. As many others do, I was looking for the CONTRIBUTING.md file in the repository, but couldn't find it. I suggest we add it with this pull request 👍

### CODE REVIEW

**Comment by una** [comment]
Hey -- have you taken a look at any of these comments yet?

**Comment by Bobeta** [comment]
I made the requested changes 👍

**Comment by una** [comment]
There's also slightly different information here: https://github.com/una/CSSgram/pull/242 with this being merged, please include that as well

**Comment by Bobeta** [comment]
There you go 👍 an idea would be to just merge it and update it on the fly as new things come along, instead of me maintaining the docs haha 😆

**Pull request merged**
