### PR TITLE
Added rise filter

### PR DESCRIPTION
**Pull request by raphaklaus**

### CODE REVIEW

**Comment by raphaelduartepinheiro** [comment]
There's an another pull request for this situation (#140). Feel free to close if necessary. :)

**Comment by raphaklaus** [comment]
Ok! Let me test it to see the diff.

**Comment by raphaklaus** [comment]
Looks fine! I've just fixed the radial-gradient without background property, and elevated the saturate value a bit. :smile:

**Comment by una** [comment]
I'm not sure it needs so much saturation -- are you checking with the test page at `http://localhost:3000/test/`?

You first will need to add `@import 'rise'` to `scss/cssgram.scss` to get it on the list

**Comment by raphaklaus** [comment]
My apologies! I didn't see the test site. Well, I think it's hard to achieve the exact same result of Instagram filter. I've tried with linear and radial gradient together and get pretty decent output. But I don't wanna extend this PR. I'm committing changes as you recommended above.

**Comment by una** [comment]
Yeah you're definitely right -- but this looks great :) thank you for your time!

**Pull request merged**
