### PR TITLE
Added Kelvin filter

### PR DESCRIPTION
**Pull request by fatimarafiqui**

### CODE REVIEW

**Comment by fatimarafiqui** [comment]
#20

**Comment by una** [comment]
Hey! Thanks for the PR -- this feels a little contrasty and warm to me. Maybe introduce some more cool shades. What do you think? (Also `contrast(1)` doesn't do anything

screen shot 2016-10-03 at 10 27 55 pm

**Comment by fatimarafiqui** [comment]
Will fix it by EOD

**Comment by una** [comment]
Whats the status on this?

**Comment by una** [comment]
Closing due to #210

**Pull request closed without merging**
