### PR TITLE
optimize png images using zopflipng

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Use Google's zopflipng to re-compress the png images losslessly as below:
```
 site/img/cssgram-logo.png | Bin 40651 -> 32022 bytes
 site/img/logo-temp.png    | Bin 15951 -> 9328 bytes
```

### CODE REVIEW

**Comment by una** [comment]
What's the cross-browser information about this?

**Comment by PeterDaveHello** [comment]
Sorry, I didn't get it, any additional info I need to provide?

**Comment by una** [comment]
Oh sorry I read this too quickly! I thought you had changed the image format. Sorry! THANKS!

**Comment by PeterDaveHello** [comment]
@una oh okay, no worry 😄

**Pull request merged**
