### PR TITLE
Sutro filter resolve #19

### LINKED ISSUE #19: Filter: Sutro

### PR DESCRIPTION
**Pull request by Stephn-R**

### CODE REVIEW

**Comment by una** [comment]
Did you have test files? for the /test page?

**Comment by Stephn-R** [comment]
No, I did not. Are those required as well?

**Comment by una** [comment]
¯\_(ツ)_/¯ it helps as a tester. Let me pink @m1 to see if he can add them

**Comment by m1** [comment]
See https://github.com/una/CSSgram/issues/96#issuecomment-157352653

**Comment by m1** [comment]
@Stephn-R I wouldn't worry about the test page for now.

**Comment by shelune** [comment]
Hey Stephn how did you manage to limit the changes just to the scss and css files?

Everytime I run gulp it changes all the structures in css and html files...

**Comment by una** [comment]
@shelune you can git rm --cached individual files to remove them from staging but keep them on your system

**Comment by Stephn-R** [comment]
Yeah the PR has been updated to modify only the affected files

**Comment by jagtalon** [comment]
@Stephn-R here are some Sutro-fied test images that you can add to the `ref` directory.

img_4568
img_4569
img_4570
img_4571
img_4572

**Comment by jagtalon** [comment]
@Stephn-R looks like you might need some kind of `radial-gradient` as well to have that halo effect going on like in Earlybird: https://github.com/una/CSSgram/blob/26ad3995304487a3d774b8688a5857471679abb7/source/scss/earlybird.scss#L14

**Comment by Stephn-R** [comment]
@jagtalon do you know if those colors are general or how they are picked out?

**Comment by jagtalon** [comment]
I'm not sure how @una does it, but it's mostly me just playing around with different combinations of blend modes (https://css-tricks.com/almanac/properties/m/mix-blend-mode/) and using FF's CSS filter editor (https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Edit_CSS_filters)

**Comment by jagtalon** [comment]
Having the tests in for comparison helps, too!

**Comment by una** [comment]
The tests are all added, please pull from latest to check them out! :)

**Comment by Stephn-R** [comment]
Alright, thanks @una, do we still need that radial gradient? Im not sure how its being calculated for the other filters

**Comment by una** [comment]
It seems like more of an inset box-shadow than a gradient to me, to be honest. push up your changes so we can compare to tests :smile:

**Comment by una** [comment]
Is this still being worked on? I'm going to close the issue because the structure has changed so much since.

Please resubmit if you want to add the inset shadow!

**Pull request closed without merging**
