### PR TITLE
added Sierra filter

### PR DESCRIPTION
**Pull request by shelune**
Resubmit my attempt at Sierra, please ignore the rise.css

### CODE REVIEW

**Comment by shelune** [comment]
Also it seems that lib-sass auto beautifies the .css file generated from .scss file.

Should I include .scss only or manually edit the .css so it follows the convention?

**Comment by una** [comment]
please remove the rise.css file and pull from master to get this up to date!

**Comment by shelune** [comment]
just done it

**Comment by una** [comment]
please get this updated with master and if you can, please rebase your commits into one!

**Comment by una** [comment]
Going to close because this PR got really messy and the structure of CSSgram was updated a lot. Please resubmit just the filter files!

**Pull request closed without merging**
