### PR TITLE
Add 1977, Ashby, Brooklyn, Charmes, Clarendon, Dogpatch, Gingham, Gin…

### PR DESCRIPTION
**Pull request by m1**
…za, Helena, Kelvin, Maven, Moon, Skyline, Stinson, Sutro, Toaster, Vesper and Walden to test site.

### CODE REVIEW

**Comment by m1** [comment]
@una There's quite a few filters with no issues -- see readme, shall I create these or do you wanna do it?

**Comment by una** [comment]
Yes please make them!

**Comment by m1** [comment]
@una Done, never knew there were so many instagram filters :grin:

**Comment by una** [comment]
Right?! 😜 I'll merge this as soon as I get to my computer

**Pull request merged**
